### ISSUE TITLE
name_prefix not used in routes if defined in routes.yaml file.

### ISSUE THREAD

**Issue by crayner** [Haehnchen/idea-php-annotation-plugin#170]
I use the **routes.yaml** in my bundle to define a name prefix for all controllers in the bundle.

```
controllers:
    resource: '@KookaburraSchoolAdminBundle/Controller/'
    type: annotation
    schemes: [ 'https' ]
    # this is added to the beginning of all imported route URLs
    prefix: '/school/admin'
    # this is added to the beginning of all imported route names
    name_prefix: 'school_admin__'
```

The annotation search function does not recognise the correct route,and flags incomplete routes as valid.

`$this->generateUrl('special_day_manage')` 
is found by the annotation software in the controller, but the route is actually invalid.

`$this->generateUrl('school_admin__special_day_manage')`
in not found by the annotation and is flagged a invalid, but the route is actually valid.

Please let me know if you require further information on this issue with details of what you require.
