### ISSUE TITLE
"Missing method" in service calls when using traits

### ISSUE THREAD

**Issue by Azenet** [Haehnchen/idea-php-annotation-plugin#57]
PhpStorm annotates `Missing method` in all my service calls that call a method that is in a trait.
Example :
```yml
my_service:
    class: My\Service
    calls:
        - [setContainer, ["@service_container"]] #"Missing method"
```

```php
namespace My;

use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerAwareTrait;

class Service implements ContainerAwareInterface {
    use ContainerAwareTrait;
}
```
The `ContainerAwareTrait` contains the `setContainer` method.

Using PhpStorm 2016.1.2 with plugin 0.12.120.
